reviews:
  profile: chill
  request_changes_workflow: true
  high_level_summary: true
  review_status: true
  commit_status: true
  collapse_walkthrough: true
  auto_assign_reviewers: true
  in_progress_fortune: false
  poem: false
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords:
      - "WIP"
      - "DO NOT MERGE"
    drafts: false
    base_branches:
      - "main"
  pre_merge_checks:
    title:
      mode: error
      requirements: 'Title should be concise and descriptive, ideally under 72 characters. Use imperative mood (e.g., "Add database for snippets").'
chat:
  auto_reply: true
