version: "2"
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - dogsled
    - dupword
    - durationcheck
    - embeddedstructfieldcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - forcetypeassert
    - funcorder
    - funlen
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godoclint
    - godot
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - iface
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange
    - iotamixing
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - mnd
    - modernize
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - nlreturn
    - noctx
    - noinlineerr
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - tagliatelle
    - testableexamples
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unqueryvet
    - unused
    - usestdlibvars
    - usetesting
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
  disable: []
  settings:
    asasalint:
      exclude:
        - Append
        - \.Wrapf
      use-builtin-exclusions: true
    bidichk:
      left-to-right-embedding: true
      right-to-left-embedding: true
      pop-directional-formatting: true
      left-to-right-override: true
      right-to-left-override: true
      left-to-right-isolate: true
      right-to-left-isolate: true
      first-strong-isolate: true
      pop-directional-isolate: true
    copyloopvar:
      check-alias: true
    cyclop:
      max-complexity: 10
      package-average: 0
    decorder:
      dec-order:
        - type
        - const
        - var
        - func
      ignore-underscore-vars: false
      disable-dec-order-check: false
      disable-init-func-first-check: false
      disable-dec-num-check: false
      disable-type-dec-num-check: true
      disable-const-dec-num-check: false
      disable-var-dec-num-check: false
    dogsled:
      max-blank-identifiers: 2
    dupl:
      threshold: 100
    dupword:
      keywords: []
      ignore: []
      comments-only: false
    embeddedstructfieldcheck:
      empty-line: true
      forbid-mutex: false
    errcheck:
      check-type-assertions: true
      check-blank: true
      disable-default-exclusions: false
      verbose: false
    errchkjson:
      check-error-free-encoding: false
      report-no-exported: false
    errorlint:
      errorf: true
      errorf-multi: true
      asserts: true
      comparison: true
    exhaustive:
      check:
        - switch
        - map
      default-signifies-exhaustive: true
      package-scope-only: false
      explicit-exhaustive-switch: false
      explicit-exhaustive-map: false
      default-case-required: false
    fatcontext:
      check-struct-pointers: false
    funcorder:
      constructor: true
      struct-method: true
      alphabetical: false
    funlen:
      lines: 60
      statements: 40
      ignore-comments: true
    gochecksumtype:
      default-signifies-exhaustive: true
      include-shared-interfaces: false
    gocognit:
      min-complexity: 20
    goconst:
      min-len: 2
      min-occurrences: 2
      match-constant: true
      numbers: true
      min: 2
      max: 2
      ignore-calls: false
      find-duplicates: true
      eval-const-expressions: true
    gocritic:
      enable-all: false
      disable-all: false
      enabled-checks:
        - appendCombine
        - badLock
        - badRegexp
        - badSorting
        - badSyncOnceFunc
        - boolExprSimplify
        - builtinShadow
        - builtinShadowDecl
        - commentedOutCode
        - commentedOutImport
        - deferInLoop
        - deferUnlambda
        - docStub
        - dupImport
        - dupOption
        - dynamicFmtString
        - emptyDecl
        - emptyFallthrough
        - emptyStringTest
        - equalFold
        - evalOrder
        - exposedSyncMutex
        - externalErrorReassign
        - filepathJoin
        - hexLiteral
        - httpNoBody
        - hugeParam
        - importShadow
        - indexAlloc
        - initClause
        - methodExprCall
        - nestingReduce
        - nilValReturn
        - octalLiteral
        - paramTypeCombine
        - preferDecodeRune
        - preferFilepathJoin
        - preferFprint
        - preferStringWriter
        - preferWriteByte
        - ptrToRefParam
        - rangeAppendAll
        - rangeExprCopy
        - rangeValCopy
        - redundantSprint
        - regexpPattern
        - regexpSimplify
        - returnAfterHttpError
        - sliceClear
        - sloppyReassign
        - sortSlice
        - sprintfQuotedString
        - sqlQuery
        - stringConcatSimplify
        - stringXbytes
        - stringsCompare
        - syncMapLoadAndDelete
        - timeExprSimplify
        - todoCommentWithoutDetail
        - tooManyResultsChecker
        - truncateCmp
        - typeAssertChain
        - typeDefFirst
        - typeUnparen
        - uncheckedInlineErr
        - unlabelStmt
        - unnamedResult
        - unnecessaryBlock
        - unnecessaryDefer
        - weakCond
        - whyNoLint
        - yodaStyleExpr
        - zeroByteRepeat
      settings:
        captLocal:
          paramsOnly: false
        commentedOutCode:
          minLength: 10
        elseif:
          skipBalanced: false
        hugeParam:
          sizeThreshold: 70
        ifElseChain:
          minThreshold: 2
        nestingReduce:
          bodyWidth: 5
        rangeExprCopy:
          sizeThreshold: 512
          skipTestFuncs: false
        rangeValCopy:
          sizeThreshold: 128
          skipTestFuncs: false
        tooManyResultsChecker:
          maxResults: 5
        truncateCmp:
          skipArchDependent: false
        underef:
          skipRecvDeref: false
        unnamedResult:
          checkExported: true
    gocyclo:
      min-complexity: 20
    godoclint:
        default: none
        enable:
          - pkg-doc
          - single-pkg-doc
          - start-with-name
          - deprecated
          - max-len
          - no-unused-link
        options:
          max-len:
            length: 120
          require-doc:
            ignore-exported: false
            ignore-unexported: true
          start-with-name:
            include-unexported: false
    godot:
      scope: all
      period: true
      capital: true
    gomoddirectives:
      replace-local: false
      retract-allow-no-explanation: false
      exclude-forbidden: true
      ignore-forbidden: true
      toolchain-forbidden: true
      tool-forbidden: false
      go-debug-forbidden: true
      go-version-pattern: '\d\.\d+(\.0)?'
    gomodguard:
      allowed:
        modules: []
        domains:
          - golang.org
          - github.com
      blocked:
        modules: []
        versions: []
        local-replace-directives: true
    gosec:
      includes: []
      excludes: []
      severity: low
      confidence: low
      config:
        global:
          nosec: true
          show-ignored: true
          audit: false
    gosmopolitan:
      allow-time-local: false
      escape-hatches: []
    govet:
      enable-all: false
      disable-all: false
      enable:
        - appends
        - asmdecl
        - assign
        - atomic
        - atomicalign
        - bools
        - buildtag
        - cgocall
        - composites
        - copylocks
        - deepequalerrors
        - defers
        - directive
        - errorsas
        - fieldalignment
        - findcall
        - framepointer
        - hostport
        - httpmux
        - httpresponse
        - ifaceassert
        - loopclosure
        - lostcancel
        - nilfunc
        - nilness
        - printf
        - reflectvaluecompare
        - shadow
        - shift
        - sigchanyzer
        - slog
        - sortslice
        - stdmethods
        - stdversion
        - stringintconv
        - structtag
        - testinggoroutine
        - tests
        - timeformat
        - unmarshal
        - unreachable
        - unsafeptr
        - unusedresult
        - unusedwrite
        - waitgroup
      disable: []
    grouper:
      const-require-single-const: true
      const-require-grouping: true
      import-require-single-import: true
      import-require-grouping: true
      type-require-single-type: true
      type-require-grouping: true
      var-require-single-var: false
      var-require-grouping: false
    iface:
      enable:
        - identical
        - unused
        - opaque
        - unexported
    importas:
      no-unaliased: false
      no-extra-aliases: false
    inamedparam:
      skip-single-param: false
    ineffassign:
      check-escaping-errors: false
    interfacebloat:
      max: 10
    iotamixing:
      report-individual: true
    lll:
      line-length: 120
      tab-width: 1
    loggercheck:
      kitlog: false
      klog: false
      logr: false
      slog: true
      zap: false
      require-string-key: true
      no-printf-like: true
    maintidx:
      under: 20
    makezero:
      always: true
    misspell:
      locale: US
      ignore-rules: []
      mode: default
    mnd:
      checks:
        - argument
        - case
        - condition
        - operation
        - return
        - assign
      ignored-files:
        - '.+_test.go'
    modernize:
      disable: []
    musttag:
      functions: []
    nakedret:
      max-func-lines: 30
    nestif:
      min-complexity: 5
    nilnil:
      only-two: true
      detect-opposite: true
      checked-types:
        - chan
        - func
        - iface
        - map
        - ptr
        - uintptr
        - unsafeptr
    nlreturn:
      block-size: 1
    nolintlint:
      allow-unused: false
      allow-no-explanation: []
      require-explanation: true
      require-specific: true
    nonamedreturns:
      report-error-in-defer: true
    paralleltest:
      ignore-missing: false
      ignore-missing-subtests: false
    perfsprint:
      integer-format: true
      int-conversion: true
      error-format: true
      err-error: true
      errorf: true
      string-format: true
      sprintf1: true
      strconcat: true
      bool-format: true
      hex-format: true
      concat-loop: true
      loop-other-ops: true
    predeclared:
      ignore: []
      qualified-name: true
    promlinter:
      strict: true
      disabled-linters: []
    protogetter:
      skip-generated-by: []
      skip-files: []
      skip-any-generated: false
      replace-first-arg-in-append: false
    reassign:
      patterns:
        - "EOF"
        - "Err.*"
    recvcheck:
      disable-builtin: false
      exclusions: []
    revive:
      max-open-files: 2048
      severity: error
      enable-all-rules: true
      directives:
        - name: specify-disable-reason
          severity: error
      confidence: 0.8
      rules:
        - name: add-constant
          severity: warning
          disabled: false
          exclude: [""]
          arguments:
            - max-lit-count: "3"
              allow-strs: '""'
              allow-ints: "0,1,2"
              allow-floats: "0.0,0.,1.0,1.,2.0,2."
        - name: line-length-limit
          severity: warning
          disabled: false
          exclude: [""]
          arguments: [120]
        - name: flag-parameter
          severity: warning
          disabled: false
          exclude: [""]
    rowserrcheck:
      packages: []
    sloglint:
      no-mixed-args: true
      kv-only: false
      attr-only: false
      no-global: "all"
      context: "all"
      static-msg: false
      msg-style: lowercased
      no-raw-keys: true
      key-naming-case: kebab
      forbidden-keys: []
      args-on-sep-lines: true
    spancheck:
      checks:
        - end
        - record-error
        - set-status
      ignore-check-signatures: []
      extra-start-span-signatures: []
    tagalign:
      align: true
      sort: true
      order:
        - json
        - yaml
        - yml
        - toml
        - mapstructure
        - binding
        - validate
      strict: true
    tagliatelle:
      case:
        rules:
          json: camel
          yaml: camel
          xml: camel
          toml: camel
          bson: camel
          avro: snake
          mapstructure: kebab
          env: upperSnake
          envconfig: upperSnake
          whatever: snake
        use-field-name: true
        ignored-fields: []
        overrides: []
    testifylint:
      enable-all: false
      disable-all: false
      disable: []
      enable:
        - blank-import
        - bool-compare
        - compares
        - contains
        - empty
        - encoded-compare
        - equal-values
        - error-is-as
        - error-nil
        - expected-actual
        - float-compare
        - formatter
        - go-require
        - len
        - negative-positive
        - nil-compare
        - regexp
        - require-error
        - suite-broken-parallel
        - suite-dont-use-pkg
        - suite-extra-assert-call
        - suite-method-signature
        - suite-subtest-run
        - suite-thelper
        - useless-assert
      bool-compare:
        ignore-custom-types: false
      formatter:
        check-format-string: true
        require-f-funcs: true
        require-string-msg: true
      go-require:
        ignore-http-handlers: false
      require-error:
        fn-pattern: ""
      suite-extra-assert-call:
        mode: remove
    thelper:
      test:
        first: true
        name: true
        begin: true
      benchmark:
        first: true
        name: true
        begin: true
      tb:
        first: true
        name: true
        begin: true
      fuzz:
        first: true
        name: true
        begin: true
    unconvert:
      fast-math: true
      safe: false
    unparam:
      check-exported: true
    unqueryvet:
      check-sql-builders: true
    unused:
      field-writes-are-uses: true
      post-statements-are-reads: true
      exported-fields-are-used: true
      parameters-are-used: true
      local-variables-are-used: false
      generated-is-used: false
    usestdlibvars:
      http-method: true
      http-status-code: true
      time-date-month: true
      time-weekday: true
      time-month: true
      time-layout: true
      crypto-hash: true
      default-rpc-path: true
      sql-isolation-level: true
      tls-signature-scheme: true
      constant-kind: true
    usetesting:
      os-create-temp: true
      os-mkdir-temp: true
      os-setenv: true
      os-temp-dir: true
      os-chdir: true
      context-background: true
      context-todo: true
    varnamelen:
      max-distance: 5
      min-name-length: 2
      check-receiver: true
      check-return: true
      check-type-param: true
      ignore-type-assert-ok: true
      ignore-map-index-ok: true
      ignore-chan-recv-ok: true
      ignore-names:
        - err
      ignore-decls: []
    whitespace:
      multi-if: true
      multi-func: false
    wrapcheck:
      report-internal-errors: true
  exclusions:
    generated: lax
    warn-unused: true
    presets:
      - comments
      - std-error-handling
      - common-false-positives
      - legacy
    rules:
      - path: ".*_test\\.go"
        linters:
          - errcheck
          - dupl
          - lll
          - revive
          - varnamelen
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
    - swaggo
  settings:
    gci:
      sections:
        - standard
        - default
        - blank
        - dot
        - alias
        - localmodule
      no-inline-comments: true
      no-prefix-comments: true
      custom-order: true
      no-lex-order: false
    gofmt:
      simplify: true
      rewrite-rules: []
    gofumpt:
      extra-rules: true
    golines:
      max-len: 120
      tab-len: 2
      shorten-comments: true
      reformat-tags: true
      chain-split-dots: false
  exclusions:
    warn-unused: true
    generated: lax
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: true
  new: false
  fix: false
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
      colors: true
  sort-order:
    - linter
    - severity
    - file
  show-stats: true
run:
  timeout: "5m"
  relative-path-mode: gitroot
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: false
  allow-serial-runners: false
  go: "1.25"
  concurrency: 4
severity:
  default: eror
  rules:
    - linters:
        - dupl
      severity: info
